version: '3'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: swag_lab_test
    container_name: test-container_swag_lab
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub
      - BASE_URL=https://www.saucedemo.com
    volumes:
      - ./target/surefire-reports:/app/target/surefire-reports
      - ./target/allure-results:/app/target/allure-results
      - ./logs:/app/logs
      - ./src/test/resources/test.conf:/app/src/test/resources/test.conf
    depends_on:
      selenium-hub:
        condition: service_healthy


